"""Corrigiendo problema de relaciones auto-referencia

Revision ID: 06b2ad018275
Revises: e3d16acf8c63
Create Date: 2025-06-23 12:43:33.429545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b2ad018275'
down_revision: Union[str, Sequence[str], None] = 'e3d16acf8c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
