"""agregando order a section_execution

Revision ID: 0c9e37e5bb1b
Revises: d23470871351
Create Date: 2025-08-04 12:15:17.009350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c9e37e5bb1b'
down_revision: Union[str, Sequence[str], None] = 'd23470871351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section_execution', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section_execution', 'order')
    # ### end Alembic commands ###
