"""on template_section delete set null in section

Revision ID: 29509a02cc7d
Revises: 7f6c0d3a2c17
Create Date: 2025-08-19 11:56:32.502553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29509a02cc7d'
down_revision: Union[str, Sequence[str], None] = '7f6c0d3a2c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('section_document_id_fkey'), 'section', type_='foreignkey')
    op.create_foreign_key(None, 'section', 'document', ['document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.create_foreign_key(op.f('section_document_id_fkey'), 'section', 'document', ['document_id'], ['id'])
    # ### end Alembic commands ###
