"""orgId en document type

Revision ID: 2ed9c11ad5cb
Revises: cb867bcc24ad
Create Date: 2025-09-24 10:17:45.141229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed9c11ad5cb'
down_revision: Union[str, Sequence[str], None] = 'cb867bcc24ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_type', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'document_type', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_type', type_='foreignkey')
    op.drop_column('document_type', 'organization_id')
    # ### end Alembic commands ###
