"""agregando campos a tabla usuario

Revision ID: 418f4e2c3051
Revises: 7191fc0f4985
Create Date: 2025-12-02 11:41:55.277817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime, timezone
import os
import uuid

# revision identifiers, used by Alembic.
revision: str = '418f4e2c3051'
down_revision: Union[str, Sequence[str], None] = '7191fc0f4985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    authtype_enum = sa.Enum('internal', 'entra', name='authtypeenum')
    user_status_enum = sa.Enum('pending', 'active', 'rejected', name='userstatus')

    op.create_table('auth_types',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', authtype_enum, nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    # Crear enum explícitamente antes de usarlo en alter table
    user_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('birthdate', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_root_admin', sa.Boolean(), nullable=True))
    op.add_column(
        'users',
        sa.Column('status', user_status_enum, nullable=False, server_default='pending')
    )
    op.alter_column('users', 'status', server_default=None)
    op.add_column('users', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('auth_type', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_foreign_key('fk_users_auth_type', 'users', 'auth_types', ['auth_type'], ['id'])
    op.drop_column('users', 'username')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
    
    admin_email = os.getenv('ADMIN_EMAIL')
    if admin_email:
        # Crear tipo de autenticación interna
        auth_type_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc)
        
        op.execute(f"""
            INSERT INTO auth_types (id, name, type, created_at, updated_at)
            VALUES ('{auth_type_id}', 'INTERNAL', 'internal', '{now}', '{now}')
        """)
        
        # Crear usuario root admin
        user_id = str(uuid.uuid4())
        op.execute(f"""
            INSERT INTO users (id, email, name, last_name, is_root_admin, status, activated_at, auth_type, created_at, updated_at)
            VALUES ('{user_id}', '{admin_email}', 'Root', 'Admin', true, 'active', '{now}', '{auth_type_id}', '{now}', '{now}')
        """)
    else:
        raise ValueError("ADMIN_EMAIL environment variable is not set. Cannot create root admin user.")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_auth_type")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_auth_type_fkey")
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'auth_type')
    op.drop_column('users', 'user_metadata')
    op.drop_column('users', 'external_id')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'activated_at')
    op.drop_column('users', 'status')
    op.drop_column('users', 'is_root_admin')
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'name')
    op.drop_table('auth_types')
    user_status_enum = sa.Enum(name='userstatus')
    user_status_enum.drop(op.get_bind(), checkfirst=True)
    authtype_enum = sa.Enum(name='authtypeenum')
    authtype_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
