"""Dejando prompt nulleable

Revision ID: 5aea39552f66
Revises: f154306d7013
Create Date: 2025-06-25 14:41:50.878633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aea39552f66'
down_revision: Union[str, Sequence[str], None] = 'f154306d7013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section', 'prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section', 'prompt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
