"""agregar tabla de llm_providers

Revision ID: 6bed7fd42a46
Revises: be90982b378a
Create Date: 2025-11-11 11:44:56.064754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bed7fd42a46'
down_revision: Union[str, Sequence[str], None] = 'be90982b378a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('deployment', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('llm', sa.Column('internal_name', sa.String(), nullable=True))
    op.add_column('llm', sa.Column('provider_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_llm_provider_id', 'llm', 'provider', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_llm_provider_id', 'llm', type_='foreignkey')
    op.drop_column('llm', 'provider_id')
    op.drop_column('llm', 'internal_name')
    op.drop_table('provider')
    # ### end Alembic commands ###
