"""on section_execution set null when delete section

Revision ID: 6f5e1cb5e340
Revises: cb10997265b1
Create Date: 2025-08-19 12:11:12.915999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5e1cb5e340'
down_revision: Union[str, Sequence[str], None] = 'cb10997265b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section_execution', 'section_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('section_execution_section_id_fkey'), 'section_execution', type_='foreignkey')
    op.create_foreign_key(None, 'section_execution', 'section', ['section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section_execution', type_='foreignkey')
    op.create_foreign_key(op.f('section_execution_section_id_fkey'), 'section_execution', 'section', ['section_id'], ['id'])
    op.alter_column('section_execution', 'section_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
