"""agregando nombre a la ejecución

Revision ID: 7191fc0f4985
Revises: 1e082404ace7
Create Date: 2025-12-01 12:52:18.750715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7191fc0f4985'
down_revision: Union[str, Sequence[str], None] = '1e082404ace7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columna como nullable primero
    op.add_column('execution', sa.Column('name', sa.String(), nullable=True))
    
    # Llenar registros existentes con valor por defecto
    op.execute("UPDATE execution SET name = 'Execution' WHERE name IS NULL")
    
    # Cambiar a not nullable
    op.alter_column('execution', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution', 'name')
    # ### end Alembic commands ###
