"""Añadir carpetas

Revision ID: 759cb8d92747
Revises: 1d330b0316c7
Create Date: 2025-09-02 11:08:02.881801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759cb8d92747'
down_revision: Union[str, Sequence[str], None] = '1d330b0316c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('parent_folder_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_document_folder_id', 'document', 'folder', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_document_folder_id', 'document', type_='foreignkey')
    op.drop_column('document', 'folder_id')
    op.drop_table('folder')
    # ### end Alembic commands ###
