"""agregar descripción en template

Revision ID: 7790f80e8218
Revises: c4e847051546
Create Date: 2025-07-09 14:56:48.147319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7790f80e8218'
down_revision: Union[str, Sequence[str], None] = 'c4e847051546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'description')
    # ### end Alembic commands ###
