"""incorporando tabla llms

Revision ID: 7f6c0d3a2c17
Revises: d5a2e2b0d2f1
Create Date: 2025-08-12 16:48:57.848723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6c0d3a2c17'
down_revision: Union[str, Sequence[str], None] = 'd5a2e2b0d2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # # Insertar registros iniciales
    # op.execute("""
    #     INSERT INTO llm (id, name, created_at, updated_at) VALUES 
    #     (gen_random_uuid(), 'gpt-4.1', NOW(), NOW()),
    #     (gen_random_uuid(), 'claude-sonnet-4', NOW(), NOW()),
    #     (gen_random_uuid(), 'llama-4-maverick', NOW(), NOW()),
    #     (gen_random_uuid(), 'gpt-oss', NOW(), NOW()),
    #     (gen_random_uuid(), 'granite-4', NOW(), NOW())
    # """)
    
    op.add_column('execution', sa.Column('model_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_execution_model_id', 'execution', 'llm', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_execution_model_id', 'execution', type_='foreignkey')
    op.drop_column('execution', 'model_id')
    
    # Eliminar registros específicos antes de eliminar la tabla
    # op.execute("""
    #     DELETE FROM llm WHERE name IN ('gpt-4.1', 'claude-sonnet-4', 'llama-4-maverick', 'gpt-oss', 'granite-4')
    # """)
    
    op.drop_table('llm')
    # ### end Alembic commands ###
