"""incorporando tabla llms

Revision ID: 7f6c0d3a2c17
Revises: d5a2e2b0d2f1
Create Date: 2025-08-12 16:48:57.848723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6c0d3a2c17'
down_revision: Union[str, Sequence[str], None] = 'd5a2e2b0d2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('execution', sa.Column('model_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'execution', 'llm', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'execution', type_='foreignkey')
    op.drop_column('execution', 'model_id')
    op.drop_table('llm')
    # ### end Alembic commands ###
