"""Revirtiendo a tabla Dependency

Revision ID: 980cc5d0e502
Revises: 06b2ad018275
Create Date: 2025-06-23 13:11:25.748899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980cc5d0e502'
down_revision: Union[str, Sequence[str], None] = '06b2ad018275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('document_dependency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_dependency',
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('depends_on_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['document.id'], name=op.f('document_dependency_depends_on_id_fkey')),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('document_dependency_document_id_fkey')),
    sa.PrimaryKeyConstraint('document_id', 'depends_on_id', name=op.f('document_dependency_pkey'))
    )
    op.drop_table('dependency')
    # ### end Alembic commands ###
