"""agregando campos a tabla usuario

Revision ID: 9cd8753b3d75
Revises: 7191fc0f4985
Create Date: 2025-12-02 18:19:46.106018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cd8753b3d75'
down_revision: Union[str, Sequence[str], None] = '7191fc0f4985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('birthdate', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_root_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Establecer valores por defecto para usuarios existentes
    op.execute("UPDATE users SET status = 'active', name = 'User', last_name = 'Lastname' WHERE status IS NULL OR name IS NULL OR last_name IS NULL")
    
    # Cambiar status a no nullable después de establecer valores por defecto
    op.alter_column('users', 'status', nullable=False)
    
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'user_metadata')
    op.drop_column('users', 'external_id')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'activated_at')
    op.drop_column('users', 'status')
    op.drop_column('users', 'is_root_admin')
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
