"""agregando nombre a section_exec, chunks apunta a section_exec

Revision ID: a12645f5f4ff
Revises: 6f5e1cb5e340
Create Date: 2025-08-20 10:51:27.411429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a12645f5f4ff'
down_revision: Union[str, Sequence[str], None] = '6f5e1cb5e340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('section_execution_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('chunk_section_id_fkey'), 'chunk', type_='foreignkey')
    op.create_foreign_key(None, 'chunk', 'section_execution', ['section_execution_id'], ['id'])
    op.drop_column('chunk', 'section_id')
    op.add_column('section_execution', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section_execution', 'name')
    op.add_column('chunk', sa.Column('section_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chunk', type_='foreignkey')
    op.create_foreign_key(op.f('chunk_section_id_fkey'), 'chunk', 'section', ['section_id'], ['id'])
    op.drop_column('chunk', 'section_execution_id')
    # ### end Alembic commands ###
