"""tipos de autenticación

Revision ID: a4f070881b45
Revises: 9cd8753b3d75
Create Date: 2025-12-02 18:34:37.892048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4f070881b45'
down_revision: Union[str, Sequence[str], None] = '9cd8753b3d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear la tabla auth_types
    op.create_table('auth_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('INTERNAL', 'ENTRA', name='authtypeenum'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    # Insertar el tipo de autenticación internal por defecto
    op.execute("""
        INSERT INTO auth_types (id, name, type, created_at, updated_at)
        VALUES (
            gen_random_uuid(),
            'Internal Authentication',
            'INTERNAL',
            NOW(),
            NOW()
        )
    """)
    
    # Agregar columna auth_type_id como nullable temporalmente
    op.add_column('users', sa.Column('auth_type_id', sa.UUID(), nullable=True))
    
    # Actualizar todos los usuarios existentes con el ID del tipo internal
    op.execute("""
        UPDATE users 
        SET auth_type_id = (
            SELECT id FROM auth_types WHERE type = 'INTERNAL' LIMIT 1
        )
        WHERE auth_type_id IS NULL
    """)
    
    # Hacer la columna NOT NULL
    op.alter_column('users', 'auth_type_id', nullable=False)
    
    # Crear la foreign key constraint
    op.create_foreign_key(None, 'users', 'auth_types', ['auth_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'auth_type_id')
    op.drop_table('auth_types')
    op.execute("DROP TYPE IF EXISTS authtypeenum")
    # ### end Alembic commands ###
