"""Agregando template section dependency

Revision ID: c3a6247bc824
Revises: 1aec877d13f5
Create Date: 2025-06-24 16:13:40.846437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a6247bc824'
down_revision: Union[str, Sequence[str], None] = '1aec877d13f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_section_dependency',
    sa.Column('template_section_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_template_section_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_template_section_id'], ['template_section.id'], ),
    sa.ForeignKeyConstraint(['template_section_id'], ['template_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_section_dependency')
    # ### end Alembic commands ###
