"""descripción de la migración

Revision ID: c4e847051546
Revises: 5aea39552f66
Create Date: 2025-07-09 13:37:42.363431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e847051546'
down_revision: Union[str, Sequence[str], None] = '5aea39552f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section_execution', sa.Column('prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section_execution', 'prompt')
    # ### end Alembic commands ###
