"""on template_section delete set null in section

Revision ID: cb10997265b1
Revises: 29509a02cc7d
Create Date: 2025-08-19 12:01:14.720922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb10997265b1'
down_revision: Union[str, Sequence[str], None] = '29509a02cc7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('section_template_section_id_fkey', 'section', type_='foreignkey')
    op.create_foreign_key('fk_section_template_section_id', 'section', 'template_section', ['template_section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_section_template_section_id', 'section', type_='foreignkey')
    op.create_foreign_key('section_template_section_id_fkey', 'section', 'template_section', ['template_section_id'], ['id'])
    # ### end Alembic commands ###
