"""tablas para chatbot

Revision ID: cb867bcc24ad
Revises: 759cb8d92747
Create Date: 2025-09-15 12:01:55.138584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb867bcc24ad'
down_revision: Union[str, Sequence[str], None] = '1cf61c7b4ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkpoint_writes', 'blob',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkpoint_writes', 'blob',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
