"""agregando organizacion

Revision ID: d5a2e2b0d2f1
Revises: 0c9e37e5bb1b
Create Date: 2025-08-04 15:33:41.848904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a2e2b0d2f1'
down_revision: Union[str, Sequence[str], None] = '0c9e37e5bb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    default_org_id = "06055DCC-A737-4AD7-B5E1-73BAD6DF0E0A"
    op.execute(f"INSERT INTO organization (id, name, description, created_at, updated_at) VALUES ('{default_org_id}', 'Default Organization', 'This is the default organization.', NOW(), NOW())")
    
    op.add_column('document', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute(f"UPDATE document SET organization_id = '{default_org_id}' WHERE organization_id IS NULL")
    op.alter_column('document', 'organization_id', nullable=False)
    op.create_foreign_key('fk_document_organization_id', 'document', 'organization', ['organization_id'], ['id'])
    
    op.add_column('template', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute(f"UPDATE template SET organization_id = '{default_org_id}' WHERE organization_id IS NULL")
    op.alter_column('template', 'organization_id', nullable=False)
    op.create_foreign_key('fk_template_organization_id', 'template', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_template_organization_id', 'template', type_='foreignkey')
    op.drop_column('template', 'organization_id')
    op.drop_constraint('fk_document_organization_id', 'document', type_='foreignkey')
    op.drop_column('document', 'organization_id')
    op.drop_table('organization')
    # ### end Alembic commands ###
