"""agregar columna default a llms

Revision ID: e293de5424bd
Revises: 6bed7fd42a46
Create Date: 2025-11-11 14:25:25.104485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e293de5424bd'
down_revision: Union[str, Sequence[str], None] = '6bed7fd42a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm', sa.Column('is_default', sa.Boolean(), nullable=True))
    
    op.execute("UPDATE llm SET is_default = FALSE WHERE is_default IS NULL")
    op.alter_column('llm', 'is_default', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm', 'is_default')
    # ### end Alembic commands ###
