"""Añadir tipo documento

Revision ID: e361d6b787bf
Revises: a12645f5f4ff
Create Date: 2025-08-27 16:13:13.347366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e361d6b787bf'
down_revision: Union[str, Sequence[str], None] = 'a12645f5f4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from datetime import datetime
    import uuid
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_type',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Añadir columna como nullable inicialmente
    op.add_column('document', sa.Column('document_type_id', sa.UUID(), nullable=True))
    
    # Crear tipo de documento por defecto
    default_type_id = str(uuid.uuid4())
    now = datetime.utcnow()
    
    # Insertar el tipo de documento por defecto
    op.execute(f"""
        INSERT INTO document_type (id, name, color, icon, created_at, updated_at)
        VALUES ('{default_type_id}', 'default', '#6B7280', 'document', '{now}', '{now}')
    """)
    
    # Asignar el tipo por defecto a todos los documentos existentes
    op.execute(f"""
        UPDATE document 
        SET document_type_id = '{default_type_id}' 
        WHERE document_type_id IS NULL
    """)
    
    # Hacer la columna obligatoria
    op.alter_column('document', 'document_type_id', nullable=False)
    
    # Crear la foreign key
    op.create_foreign_key('fk_document_document_type_id', 'document', 'document_type', ['document_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_document_document_type_id', 'document', type_='foreignkey')
    op.drop_column('document', 'document_type_id')
    op.drop_table('document_type')
    # ### end Alembic commands ###
