"""Generando dependencia m-m v2

Revision ID: e3d16acf8c63
Revises: 21361b869bee
Create Date: 2025-06-23 12:10:11.662413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3d16acf8c63'
down_revision: Union[str, Sequence[str], None] = '21361b869bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_dependency',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'depends_on_id')
    )
    op.drop_table('dependency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency',
    sa.Column('depends_on', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('dependency_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dependency_pkey'))
    )
    op.drop_table('document_dependency')
    # ### end Alembic commands ###
