"""Corrigiendo referencia circular

Revision ID: f154306d7013
Revises: c3a6247bc824
Create Date: 2025-06-24 16:16:33.192077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f154306d7013'
down_revision: Union[str, Sequence[str], None] = 'c3a6247bc824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_section_context_dependency_id', 'section', type_='foreignkey')
    op.drop_column('section', 'context_dependency_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('context_dependency_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_section_context_dependency_id', 'section', 'dependency', ['context_dependency_id'], ['id'])
    # ### end Alembic commands ###
